### ISSUE TITLE
strap mac mini on aws

### ISSUE THREAD

**Issue by jerryfu-okta** [strapsh/strap#9]
chef01a:~ root# cat /etc/*release 2>/dev/null | head -n1
IMAGE_NAME="amzn-ec2-macos-10.15.7-20210210-012655"
chef01a:~ root# cat /etc/*release
IMAGE_NAME="amzn-ec2-macos-10.15.7-20210210-012655"
FULL_VERSION="10.15.7-20210210-012655"
MAJOR_VERSION="10.15.7"

The output will confuse strap about it's OS.

**Comment by lhazlewood** [comment]
Fixed via #10
